language: rust
rust:
  - stable

before_script: |
  rustup component add rustfmt-preview &&
  rustup target add wasm32-unknown-uknown
script: |
  cargo fmt -- --check &&
  cargo build --verbose --target wasm32-unknown-unknown
cache: cargo
